### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by bjones1**
I added an anchor so I can reference fitb docs from Runestone Components, plus DRYed / cleaned a bit.

### CODE REVIEW

**Review by bnmnetp — COMMENTED** [review]
Removing overview.rst is going to break a LOT of external links.

**Comment by bjones1** [comment]
Oops! I'll restore the file. How about simply making it point to the index? Having two toctrees with the same contents produces Sphinx errors.

**Comment by bnmnetp** [comment]
Looks like a good job for the sphinx-redirects extension.

**Comment by bjones1** [comment]
Done and pushed! Thansks.

**Pull request merged**
